port = 3003

[[repos]]
repo = "LucaCoduriV/rust-webhook-server"
secret = "1234"
branch = "main"
repo_directory = "."
working_directory = "."
command = "./testscript.ps1"
args = ["test"]
events = ["push"]

[[repos]]
repo = "2"
location = "."
repo_directory = "."

[[repos]]
repo = "3"
location = "."
repo_directory = "."