port = 3003
git_directory = "C:\\Program Files\\Git\\cmd\\git.exe"

[[repos]]
repo = "LucaCoduriV/rust-webhook-server"
secret = "1234"
branch = "main"
repo_directory = "."
working_directory = "."
command = "powershell"
args = ["./testscript.ps1"]
events = ["push"]

[[repos]]
repo = "2"
location = "."
repo_directory = "."

[[repos]]
repo = "3"
location = "."
repo_directory = "."