use serde_enum_str::Deserialize_enum_str;
use serde_enum_str::Serialize_enum_str;

#[derive(Deserialize_enum_str, Serialize_enum_str, Debug, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum GithubEventTypes {
    BranchProtectionRule,
    CheckRun,
    CheckSuite,
    CodeScanningAlert,
    CommitComment,
    Create,
    Delete,
    DependabotAlert,
    DeployKey,
    Deployment,
    DeploymentStatus,
    Discussion,
    DiscussionComment,
    Fork,
    GithubAppAuthorization,
    Gollum,
    Installation,
    InstallationRepositories,
    InstallationTarget,
    IssueComment,
    Issues,
    Label,
    MarketplacePurchase,
    Member,
    Membership,
    MergeGroup,
    Meta,
    Milestone,
    OrgBlock,
    Organization,
    Package,
    PageBuild,
    PersonalAccessTokenRequest,
    Ping,
    ProjectCard,
    Project,
    ProjectColumn,
    ProjectV2,
    ProjectV2Item,
    Public,
    PullRequest,
    PullRequestReviewComment,
    PullRequestReview,
    PullRequestReviewThread,
    Push,
    RegistryPackage,
    Release,
    RepositoryAdvisory,
    Repository,
    RepositoryDispatch,
    RepositoryImport,
    RepositoryVulnerabilityAlert,
    SecretScanningAlert,
    SecretScanningAlertLocation,
    SecurityAdvisory,
    SecurityAndAnalysis,
    Sponsorship,
    Star,
    Status,
    TeamAdd,
    Team,
    Watch,
    WorkflowDispatch,
    WorkflowJob,
    WorkflowRun
}

